// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadConfig(arg1) {
  return window['go']['main']['App']['LoadConfig'](arg1);
}

export function SaveConfig(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveConfig'](arg1, arg2, arg3);
}
