// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadConfig(arg1:string):Promise<Array<string>>;

export function SaveConfig(arg1:string,arg2:Array<string>,arg3:number):Promise<void>;
